export const accountOptions = [
  {
    content: "帳戶資料",
    path: "/account/profile",
    route: "/myAccount/dropdownList/info-default.svg",
    active: "/myAccount/dropdownList/info-selected.svg",
    memberAccess: true,
    adminAccess: true,
    level: 1,
  },
  {
    content: "送貨地址",
    path: "/account/delivery-address",
    route: "/myAccount/dropdownList/myaddress-default.svg",
    active: "/myAccount/dropdownList/myaddress-selected.svg",
    memberAccess: true,
    adminAccess: false,
    level: 1,
  },
  {
    content: "訂單記錄",
    path: "/account/orders",
    route: "/myAccount/dropdownList/orderhistory-default.svg",
    active: "/myAccount/dropdownList/orderhistory-selected.svg",
    memberAccess: true,
    adminAccess: true,
    level: 1,
  },
  {
    content: "積分記錄",
    path: "/account/points",
    route: "/myAccount/dropdownList/pointhistory-default.svg",
    active: "/myAccount/dropdownList/pointhistory-selected.svg",
    memberAccess: true,
    adminAccess: false,
    level: 1,
  },
  {
    content: "建立果籃訂單",
    path: "/account/create-hamper-order",
    route: "/myAccount/dropdownList/orderhistory-default.svg",
    active: "/myAccount/dropdownList/orderhistory-selected.svg",
    memberAccess: false,
    adminAccess: true,
    level: 1,
  },
  {
    content: "喜愛清單",
    path: "/account/wishlist",
    route: "/myAccount/dropdownList/mylist-default.svg",
    active: "/myAccount/dropdownList/mylist-selected.svg",
    memberAccess: true,
    adminAccess: false,
    level: 2,
  },
  // {
  //   content: "曾經購買",
  //   route: "/myAccount/dropdownList/purchasehistory-default.svg",
  //   path: "/account/purchase-record",
  //   id: "6",
  // },
];