export const homeCat = [
  {
    type: "期間限定",
    route: "/seasonal-limited",
    barColor: "cat-yellow-bar",
    textColor: "cat-yellow-text",
    bgColor: "cat-yellow",
    icon: "limited.svg",
    next:"更多",
    tabs: [
      { name: "Tamashii 人氣卡通預售", route: "/tamashii" },
      { name: "一田春日美肌提案", route: "/spring-skincare" },
      { name: "一田春日嬰兒用品展", route: "/spring-bb-item" },
    ],
  },
  {
    type: "店長推介",
    route: "/recommend",
    barColor: "cat-green-bar",
    textColor: "cat-green-text",
    bgColor: "cat-green",
    icon: "recommend.svg",
    next:"更多",
    tabs: [
      { name: "抗疫推介", route: "/prevent-covid" },
      { name: "荀貨推介", route: "/good-product" },
      { name: "美妝推介", route: "/skincare" },
    ],
  },
  {
    type: "母嬰專區",
    route: "/maternal",
    barColor: "cat-pink-bar",
    textColor: "cat-pink-text",
    bgColor: "cat-pink",
    icon: "baby.svg",
    next:"更多",
    tabs: [
      { name: "新手孕媽媽必備", route: "/new-mum" },
      { name: "孕媽媽產前準備", route: "/pregnant" },
      { name: "BB媽產後護理", route: "/postpartum" },
      { name: "護理用品", route: "/diapers" },
      { name: "嬰兒服飾", route: "/postpartum" },
    ],
  },
  {
    type: "超市精選",
    route: "/supermarket",
    barColor: "cat-blue-bar",
    textColor: "cat-blue-text",
    bgColor: "cat-blue",
    icon: "supermarket.svg",
    next:"更多",
    tabs: [
      { name: "新手孕媽媽必備", route: "/new-mum" },
      { name: "孕媽媽產前準備", route: "/pregnant" },
      { name: "BB媽產後護理", route: "/postpartum" },
      { name: "護理用品", route: "/diapers" },
      { name: "嬰兒服飾", route: "/postpartum" },
    ],
  },
  {
    type: "百貨精選",
    route: "/department",
    barColor: "cat-orange-bar",
    textColor: "cat-orange-text",
    bgColor: "cat-orange",
    icon: "department.svg",
    next:"更多",

    tabs: [
      { name: "新手孕媽媽必備", route: "/new-mum" },
      { name: "孕媽媽產前準備", route: "/pregnant" },
      { name: "BB媽產後護理", route: "/postpartum" },
      { name: "護理用品", route: "/diapers" },
      { name: "嬰兒服飾", route: "/postpartum" },
    ],
  },
  {
    type: "百貨精選",
    route: "/department",
    barColor: "cat-orange-bar",
    textColor: "cat-orange-text",
    bgColor: "cat-orange",
    icon: "department.svg",
    next:"更多",
    tabs: [
      { name: "新手孕媽媽必備", route: "/new-mum" },
      { name: "孕媽媽產前準備", route: "/pregnant" },
      { name: "BB媽產後護理", route: "/postpartum" },
      { name: "護理用品", route: "/diapers" },
      { name: "嬰兒服飾", route: "/postpartum" },
    ],
  },
  {
    next:"",
    type: "百貨精選",
    route: "",
    barColor: "white",
    textColor: "yata-brown",
    bgColor: "white",
    icon: "heart-selected.svg",
    tabs: [

    ],
  },
];
